import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "FiveStar Growth privacy policy for loyalty, Wallet-pass, customer engagement, review and communication services.",
  alternates: { canonical: "/privacy/" },
};

function PolicySection({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return <section className="border-t border-white/10 py-9 sm:py-11"><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-400">{String(number).padStart(2, "0")}</p><h2 className="mt-3 text-2xl font-black tracking-[-.035em] text-white sm:text-3xl">{title}</h2><div className="mt-5 max-w-3xl space-y-5 text-[15px] leading-7 text-zinc-300 sm:text-base">{children}</div></section>;
}

function List({ children }: { children: React.ReactNode }) {
  return <ul className="grid gap-2 pl-5 marker:text-orange-400">{children}</ul>;
}

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#0a0a0a] px-5 py-16 text-white sm:px-8 sm:py-24"><article className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-400">FiveStar Growth / Legal</p><h1 className="mt-4 text-4xl font-black tracking-[-.06em] sm:text-6xl">Privacy Policy</h1><p className="mt-5 text-base text-zinc-400">Effective date: 8 August 2026</p><div className="mt-10 rounded-2xl border border-orange-500/30 bg-orange-500/10 p-5 text-zinc-200 sm:p-6">FiveStar Growth provides digital loyalty, customer engagement, Google review, promotional communication and Wallet-pass services to participating New Zealand businesses.</div><p className="mt-6 max-w-3xl leading-7 text-zinc-300">This Privacy Policy explains how FiveStar Growth collects, uses, stores and shares personal information when customers, merchants, salespeople and staff use FiveStar Growth websites, loyalty programmes, Wallet passes, dashboards and related services.</p>

  <div className="mt-12">
    <PolicySection number={1} title="Who we are"><p>FiveStar Growth operates the FiveStar Growth loyalty platform.</p><p>In this policy, “FiveStar”, “we”, “our” and “us” mean FiveStar Growth. “Merchant” means a participating business using FiveStar Growth. “Customer” means a person enrolled in a merchant’s loyalty programme. “Service” means our websites, loyalty platform, digital Wallet passes, merchant dashboards, staff checkout terminals and related communication services.</p><p><strong className="text-white">Contact</strong><br />Email: <a className="text-orange-300 underline underline-offset-4" href="mailto:hello@fivestargrowth.nz">hello@fivestargrowth.nz</a><br />Phone: 020 451 0002<br />Privacy page: <a className="text-orange-300 underline underline-offset-4" href="https://fivestargrowth.nz/privacy">https://fivestargrowth.nz/privacy</a></p></PolicySection>
    <PolicySection number={2} title="Information we collect"><h3 className="font-bold text-white">Customer information</h3><List><li>First name</li><li>Mobile number</li><li>Optional email address</li><li>Marketing consent and unsubscribe status</li><li>Merchant loyalty memberships</li><li>Points or stamp balances</li><li>Visit and transaction history</li><li>Purchase amounts or qualifying items entered by merchant staff</li><li>Rewards earned, selected and redeemed</li><li>Review-request status, including whether a review link was selected</li><li>Google Wallet or Apple Wallet pass identifiers and status</li><li>Checkout and redemption codes</li><li>Notification and communication status</li><li>Customer support communications</li></List><p>We do not collect the content or star rating of a Google review through the FiveStar platform.</p><h3 className="font-bold text-white">Location and device information</h3><p>Where enabled by a merchant and permitted by the user, we may collect approximate or precise device location to confirm that a customer is physically near a participating store.</p><List><li>Browser and device type</li><li>Operating system</li><li>IP address</li><li>Date and time of activity</li><li>Security and diagnostic logs</li><li>NFC or QR interaction information</li><li>NTAG security data, including tag identifiers, counters and authentication results</li><li>Essential cookie, session and local-storage information</li></List><h3 className="font-bold text-white">Merchant and sales-team information</h3><List><li>Owner and staff names</li><li>Business and personal contact information</li><li>Business name, category and physical address</li><li>Loyalty programme and reward settings</li><li>Subscription plan and status</li><li>Staff-device information</li><li>Salesperson assignment and referral information</li><li>Commission rates and estimated commission amounts</li><li>Dashboard activity, access and security logs</li><li>Support and onboarding communications</li></List></PolicySection>
    <PolicySection number={3} title="How we collect information"><p>We may collect information:</p><List><li>Directly from customers, merchants, salespeople and staff</li><li>When a customer enrols or uses a loyalty programme</li><li>When merchant staff confirm a purchase or redemption</li><li>Through NFC, QR, Wallet and checkout interactions</li><li>From participating merchants acting in connection with their loyalty programme</li><li>From Google Wallet, Apple Wallet, SMS and email delivery providers</li><li>Automatically through security, diagnostic and service logs</li><li>Through sales-referral and merchant-onboarding links</li></List><p>Where information is supplied by a merchant or another authorised person, we use it only for operating the relevant FiveStar service and related lawful purposes.</p></PolicySection>
    <PolicySection number={4} title="Why we use personal information"><p>We use personal information to:</p><List><li>Create and manage loyalty accounts</li><li>Identify returning customers</li><li>Award and deduct points or stamps</li><li>Display balances, rewards and progress</li><li>Create and update digital Wallet passes</li><li>Process reward redemptions</li><li>Confirm customer visits and purchases</li><li>Prevent duplicate taps, misuse and fraudulent activity</li><li>Apply merchant cooldown and location rules</li><li>Display customers awaiting service on an authorised staff terminal</li><li>Deliver transactional SMS, email and Wallet updates</li><li>Deliver promotional communications where consent has been given</li><li>Present Google review requests according to merchant settings</li><li>Provide merchant dashboards, reports and customer activity</li><li>Operate sales attribution and commission reporting</li><li>Respond to support and privacy requests</li><li>Protect the security and reliability of the Service</li><li>Meet legal, accounting and regulatory obligations</li></List></PolicySection>
    <PolicySection number={5} title="Promotional communications and consent"><p>Providing an email address for promotional offers is optional. A customer does not need to provide an email address to collect loyalty points, obtain a Wallet pass, redeem a reward or use the Service.</p><p>Promotional email consent is merchant-specific. Consent to receive offers from one merchant does not give another merchant permission to send promotional email.</p><p>We only save a promotional email address when the customer actively submits the promotional-email form.</p><p>Marketing messages will identify the relevant merchant or FiveStar Growth and include an unsubscribe facility.</p><p>Customers may:</p><List><li>Use the unsubscribe link in an email</li><li>Reply STOP to supported promotional SMS messages</li><li>Disable Wallet notifications through their device</li><li>Remove a Wallet pass</li><li>Contact FiveStar Growth or the relevant merchant</li></List><p>When a promotional-email unsubscribe is processed, promotional consent is disabled, the plaintext email address is removed from the active subscription record, and a one-way email hash may be retained as a suppression record. The suppression record helps prevent the address from being accidentally added to or contacted through a future campaign.</p></PolicySection>
    <PolicySection number={6} title="Transactional communications"><p>We may send communications necessary to operate a loyalty account, such as:</p><List><li>Account and Wallet-pass confirmations</li><li>Points, stamps and reward updates</li><li>Redemption information</li><li>Security notices</li><li>Important service changes</li><li>Responses to support requests</li></List><p>Transactional communications are separate from optional promotional-email consent, although users may still control applicable Wallet and device-notification settings.</p></PolicySection>
    <PolicySection number={7} title="How merchants use information"><p>A merchant may access information connected with its own loyalty programme, including customer identity, loyalty balance, visit history, transaction details and redemption activity.</p><p>Merchants cannot access another merchant’s customer data through FiveStar.</p><p>Merchants are responsible for using customer information lawfully and only for legitimate loyalty, service and consented marketing purposes.</p></PolicySection>
    <PolicySection number={8} title="When we share information"><p>We may share personal information with:</p><List><li>The participating merchant whose loyalty programme the customer joined</li><li>Hosting, database and infrastructure providers</li><li>SMS and email delivery providers</li><li>Google Wallet and Apple Wallet</li><li>Security, encryption and authentication providers</li><li>Professional advisers, insurers or regulators where necessary</li><li>Government or law-enforcement authorities where legally required</li><li>A purchaser or successor if the FiveStar business is reorganised or transferred, subject to appropriate privacy protections</li></List><p>Service providers may include Supabase, Vercel, Twilio, Resend or Postmark, Google, Apple and Amazon Web Services.</p><p>We do not sell customer personal information.</p></PolicySection>
    <PolicySection number={9} title="Overseas processing"><p>Some technology providers may process or store information outside New Zealand, including in Australia, the United States or other countries.</p><p>Where personal information is disclosed overseas, we will take reasonable steps to ensure the recipient provides privacy safeguards consistent with New Zealand privacy requirements.</p></PolicySection>
    <PolicySection number={10} title="Security"><p>We use reasonable technical and organisational safeguards designed to protect personal information, including:</p><List><li>Encrypted network connections</li><li>Restricted administrative access</li><li>Hashed access credentials and sensitive identifiers</li><li>Merchant-specific access controls</li><li>Signed customer, unsubscribe and redemption links</li><li>Database constraints and transaction controls</li><li>Security logging</li><li>NFC authentication and replay protections where supported</li><li>Staff-device revocation controls</li></List><p>No internet or storage system can be guaranteed to be completely secure. Customers and merchants should protect their devices, passwords, access keys and accounts.</p></PolicySection>
    <PolicySection number={11} title="Retention"><p>We retain personal information only for as long as reasonably necessary to provide the Service, maintain accurate loyalty and redemption records, resolve disputes, prevent fraud or duplicate use, and meet legal, accounting and security obligations.</p><p>Information may be anonymised or deleted when it is no longer required. Suppression hashes may be retained after an email unsubscribe to ensure the address is not accidentally contacted again.</p></PolicySection>
    <PolicySection number={12} title="Access, correction and deletion"><p>Individuals may ask us to:</p><List><li>Confirm whether we hold their personal information</li><li>Provide access to their personal information</li><li>Correct inaccurate or incomplete information</li><li>Delete information that is no longer required</li><li>Withdraw promotional consent</li><li>Explain how their information has been used or disclosed</li></List><p>Requests can be sent to <a className="text-orange-300 underline underline-offset-4" href="mailto:hello@fivestargrowth.nz">hello@fivestargrowth.nz</a>.</p><p>We may need to verify the requester’s identity before providing or changing personal information. Some information may need to be retained where required for security, legal, transaction or fraud-prevention purposes.</p></PolicySection>
    <PolicySection number={13} title="Cookies, sessions and local storage"><p>Our websites and installed web applications may use essential cookies, browser storage and session information to:</p><List><li>Keep authorised users signed in</li><li>Pair staff checkout devices</li><li>Maintain secure sessions</li><li>Support PWA installation and offline loading</li><li>Protect the Service</li><li>Improve reliability and loading performance</li></List><p>We do not currently use this information for third-party behavioural advertising.</p></PolicySection>
    <PolicySection number={14} title="Automated loyalty and security rules"><p>The Service may automatically:</p><List><li>Calculate points or stamps</li><li>Determine reward eligibility</li><li>Enforce tap cooldowns</li><li>Reject invalid or duplicated NFC interactions</li><li>Apply merchant reward settings</li><li>Check optional store-distance requirements</li></List><p>Merchants remain responsible for confirming purchases and redemptions where staff confirmation is required.</p></PolicySection>
    <PolicySection number={15} title="Privacy breaches"><p>If a privacy breach occurs that has caused or is likely to cause serious harm, we will notify the Office of the Privacy Commissioner and affected individuals as required by the Privacy Act 2020.</p></PolicySection>
    <PolicySection number={16} title="Complaints"><p>Privacy concerns should first be sent to:</p><p><strong className="text-white">Privacy Officer</strong><br />FiveStar Growth<br />Email: <a className="text-orange-300 underline underline-offset-4" href="mailto:hello@fivestargrowth.nz">hello@fivestargrowth.nz</a><br />Phone: 020 451 0002</p><p>We will investigate and respond to privacy concerns within a reasonable period.</p><p>Individuals may also contact the New Zealand Office of the Privacy Commissioner: <a className="text-orange-300 underline underline-offset-4" href="https://www.privacy.org.nz/" target="_blank" rel="noreferrer">https://www.privacy.org.nz</a>.</p></PolicySection>
    <PolicySection number={17} title="Changes to this policy"><p>We may update this Privacy Policy when our services, providers or legal obligations change.</p><p>The latest version will always be available at <a className="text-orange-300 underline underline-offset-4" href="https://fivestargrowth.nz/privacy">https://fivestargrowth.nz/privacy</a>.</p><p>Material changes may also be communicated through the Service, by email or through merchant communications.</p></PolicySection>
  </div>
  </article></main>;
}
